{% set name = "pytask-parallel" %}
{% set version = "0.4.0rc1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytask_parallel-{{ version }}.tar.gz
  sha256: 06476af720e7029086c71f2f28bc1eaf30ba6d0bb66bd58c39594438a8de5841

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools_scm
    - toml
  run:
    - click
    - cloudpickle
    - loky
    - optree >=0.9.0
    - pytask >=0.4.0rc2
    - python >=3.8
    - rich

test:
  imports:
    - pytask_parallel
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pytask-dev/pytask-parallel
  summary: Parallelize the execution of pytask.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/pytask-dev/pytask-parallel
  doc_url: https://github.com/pytask-dev/pytask-parallel

extra:
  recipe-maintainers:
    - tobiasraabe
