{% set name = "pytask-parallel" %}
{% set version = "0.0.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytask-parallel-{{ version }}.tar.gz
  sha256: 1b0ac00f9d6bf26a93cb5442c89c3c9e25a5ef8a2d58e34619dff64717eb2466

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - cloudpickle
    - loky
    - pytask >=0.0.11
    - python >=3.6

test:
  imports:
    - pytask_parallel
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pytask-dev/pytask-latex
  summary: Parallelize the execution of pytask.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/pytask-dev/pytask-latex
  doc_url: https://github.com/pytask-dev/pytask-latex

extra:
  recipe-maintainers:
    - tobiasraabe
