{% set name = "pytask-parallel" %}
{% set version = "0.3.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytask_parallel-{{ version }}.tar.gz
  sha256: beb5aa154806469105346044f8ed7825eef4de7e0c9978579afe2b5c0a85e48c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools_scm
    - toml
  run:
    - attrs >=21.3.0
    - click
    - cloudpickle
    - loky
    - pybaum >=0.1.1
    - pytask >=0.3
    - python >=3.7
    - rich

test:
  imports:
    - pytask_parallel
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pytask-dev/pytask-parallel
  summary: Parallelize the execution of pytask.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/pytask-dev/pytask-parallel
  doc_url: https://github.com/pytask-dev/pytask-parallel

extra:
  recipe-maintainers:
    - tobiasraabe
