{% set name = "pytask-parallel" %}
{% set version = "0.5.2" %}
{% set python_min = "3.9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pytask_parallel-{{ version }}.tar.gz
  sha256: 8c8678b7089ab2542b7de989497ffb6f08600aba56ac7e4414edb10442e96359

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
  run:
    - attrs >=21.3.0
    - click
    - cloudpickle
    - loky
    - pluggy >=1.0.0
    - pytask >=0.5.2
    - python >={{ python_min }}
    - rich

test:
  imports:
    - pytask_parallel
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pytask-dev/pytask-parallel
  summary: Parallelize the execution of pytask.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/pytask-dev/pytask-parallel
  doc_url: https://pytask-parallel.readthedocs.io/

extra:
  recipe-maintainers:
    - tobiasraabe
