{% set name = "pytask-parallel" %}
{% set version = "0.5.0" %}
{% set python_min = "3.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pytask_parallel-{{ version }}.tar.gz
  sha256: 9c58bdf2dbab3bbd51106d7bc43fbeac6d9d081ffe7e510d1f33f95df6d9c013

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
  run:
    - attrs >=21.3.0
    - click
    - cloudpickle
    - loky
    - pluggy >=1.0.0
    - pytask >=0.5.0
    - python >={{ python_min }}
    - rich

test:
  imports:
    - pytask_parallel
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pytask-dev/pytask-parallel
  summary: Parallelize the execution of pytask.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/pytask-dev/pytask-parallel
  doc_url: https://pytask-parallel.readthedocs.io/

extra:
  recipe-maintainers:
    - tobiasraabe
