{% set name = "pytask-parallel" %}
{% set version = "0.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytask_parallel-{{ version }}.tar.gz
  sha256: 30beda6460774255007f8f6fb14f73b121f1295adc4071e01b9bd6780a3f6628

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools_scm
    - toml
  run:
    - cloudpickle
    - loky
    - pytask >=0.2
    - python >=3.7

test:
  imports:
    - pytask_parallel
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pytask-dev/pytask-parallel
  summary: Parallelize the execution of pytask.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/pytask-dev/pytask-parallel
  doc_url: https://github.com/pytask-dev/pytask-parallel

extra:
  recipe-maintainers:
    - tobiasraabe
